# Generated by Django 5.0.3 on 2024-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOOK_TITLE', models.CharField(max_length=30)),
                ('YEAR_OF_PUBLISH', models.DateField()),
                ('AUTHOR_NAME', models.CharField(max_length=20)),
                ('NO_OF_PAGE', models.IntegerField()),
                ('BOOK_PRICE', models.IntegerField()),
            ],
        ),
    ]
